env:
  node: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - "plugin:fp/recommended"
plugins:
  - jest
  - fp
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutating-methods:
    - error
    - allowedObjects:
      - "_"